### PR TITLE
Ch/#159261735/implement feedback

### PR DESCRIPTION
**Pull request by sulenchy**
### What does this PR do?
Implement feedback received on UI

#### Description of Task to be completed?
- Add overlay to the landing page.
- Change the background image in the landing page.
- Apply border radius to the login modal.
- Fix the typo
- Reduce the font size of the typo
- Remove the help link

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
Feedback received on UI

#### What are the relevant pivotal tracker stories?
Implement feedback received in Day 1

#### Screenshots (if appropriate)
screencapture-file-c-users-sulenchy-documents-code-mydiary-ui-user-entries-html-2018-07-24-13_32_05
screencapture-file-c-users-sulenchy-documents-code-mydiary-ui-index-html-2018-07-24-13_31_37
screencapture-file-c-users-sulenchy-documents-code-mydiary-ui-index-html-2018-07-24-12_47_04
screencapture-file-c-users-sulenchy-documents-code-mydiary-ui-entry-content-html-2018-07-24-13_32_58

#### Questions:
N/A

### CODE REVIEW

**Comment by fob413** [comment]
Add padding top to the login form, so there's some space at d top of the modal

**Comment by fob413** [comment]
On your dashboard/entries page, add some space between the side nav and the text touching it. That's for both the all entries and single entries page

**Comment by fob413** [comment]
Go ahead and merge

**Comment by sulenchy** [comment]
Alright. Thanks

**Pull request merged**
